### ISSUE TITLE
Pop ups are missing or the packages doesn't work

### ISSUE THREAD

**Issue by ehernandez-xk** [zmb3/godoc#12]
Hi everyone

I want to use this package, I installed it on Atom _Preferences_, and ran `go get github.com/zmb3/gogetdoc`  I followed the instructions in **Usage** section.

But the pop ups are missing in my go code.

Any idea what I missing ?

**Comment by zmb3** [comment]
What's your setup look like:
- OS?
- Atom Version?
- Go Version?

Did the `go get` operation succeed?  Can you run `gogetdoc` from the command line?

**Comment by ehernandez-xk** [comment]
Hi, sorry for the poor info

Here you have my local setup:

- OS X Yosemite
- Atom 1.0.5
- Go version go1.6 darwin/amd6

`go get github.com/zmb3/gogetdoc` was success
`gogetdoc` shows:
missing required -pos flag

**Comment by zmb3** [comment]
The current stable version of Atom is 1.6.0.  Can we start by trying to update Atom?

**Comment by ehernandez-xk** [comment]
yuju, it works

After a long time trying to update Atom, I uninstalled and installed Atom with the latest version 1.6.2

Thank you.

**Comment by zmb3** [comment]
No problem.  Keep an eye out for updates on this package and `gogetdoc`.  I'll be cleaning this up a bit soon.
