### ISSUE TITLE
Cannot get this to work

### ISSUE THREAD

**Issue by momirDjekic** [zmb3/godoc#16]
My setup is:
OS X El Capitain 10.11.4
Atom 1.7.3
Go go1.6 darwin/amd64

When I try to use godoc, by clicking Alt+D, I get a loading image and it never gets loaded.
$GOPATH/bin is is in my $PATH

Build has a green status passing

**Comment by zmb3** [comment]
Is `gogetdoc` on your path?  Can you try to run it manually from the command line?

Also, could you try to open up the dev tools (cmd+option+i) and then try to get doc with Alt+D and let me know if you see any sort of error in the console?

**Comment by momirDjekic** [comment]
Just tried it from the command line and it works.

When I invoke the console, I can see that **godoc.js:85 stdout:** appears.
Nothing is printed to the console...
