### ISSUE TITLE
Documentation paragraph format is incorrectly parsed at times

### ISSUE THREAD

**Issue by VinayGupta23** [zmb3/godoc#18]
I have just installed the `godoc` tool for Atom, and I believe there are certain issues with how the documentation is being displayed.

The recommended way to document code is described [here](https://blog.golang.org/godoc-documenting-go-code), and it is exactly what I'm doing. However I noticed that somehow the parser seems to append new line at random locations, which makes the documentation look very broken and poorly justified.

This is an example from a built-in library by the Go creators, which I believe displayed incorrectly:
![library doc example](https://cloud.githubusercontent.com/assets/8874825/16160287/f1a1b470-34e4-11e6-9dfa-aa4485fefe19.PNG)

And another from a file I've written:
![ex2](https://cloud.githubusercontent.com/assets/8874825/16160318/0d8b17b2-34e5-11e6-8092-c62cd0edf517.PNG)

This does not happen always, and these are some examples where they do. Please check up on the same.

P.S. I really look forward to using this tool extensively, so I would appreciate any feedback and correction. Thanks!

**Comment by zmb3** [comment]
Thanks for the report. You aren't doing anything wrong, the tool is just
wrapping lines at 80 chars.

I'm currently working on some UI updates that will fix this and improve the
overall feel of the package.  You can expect a fix for this in the next few
days :)

**Comment by VinayGupta23** [comment]
That's great, I'll keep a look out :)

**Comment by zmb3** [comment]
Fixed in release 0.3.0 (461488a4b6075aa19541a7614898515b344b0c43)
